# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CLICK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  source 'https://github.com/CocoaPods/Specs.git'
  pod 'SwiftyJSON', '~>5.0.0'
  pod 'SnapKit', '~>5.0.0'
  pod 'Moya/RxSwift'
  pod 'RxCocoa'
  pod 'MBProgressHUD', '~>1.1.0'
  pod 'HandyJSON'
  pod 'IQKeyboardManagerSwift', '~>6.3.0'
  pod 'MJRefresh'
  pod 'HXPhotoPicker', '~> 3.3.1'
  pod 'SDWebImage'
  
  pod 'FSCalendar' #日历

    
  
  #谷歌地图
  pod'GoogleMaps'
  pod'GooglePlaces'
  
  pod 'Firebase/Auth'
  
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
  pod 'FirebaseUI/Phone'
  pod 'FirebaseUI/OAuth' # Used for Sign in with Apple, Twitter, etc

  pod 'Firebase/Messaging'

  # Pods for CLICK

   pod 'Stripe'
  
  
  
  
  target 'CLICKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CLICKUITests' do
    # Pods for testing
  end

end
